### ISSUE TITLE
Not seeing half of the commands

### ISSUE THREAD

**Issue by hwaarl** [apigee/Sweetlime#6]
Hi,
I finally got Sweetlime working on ST3 - (worth noting in the readme! ST2 doesn't work, don't bother debugging the python)
But I'm missing half of the command (Ctrl-Shift P), notably the ability to create a new proxy and initiate a project in the first place. What's wrong? Is github up to date?
Cheers,
Hans

**Comment by durkode** [comment]
I am having a similar issue. Of the 6 actions listed in Default.sublime-commands, 2 of them are missing from the command palette (Ctrl+Shift+P): New Proxy and Deploy Proxy.

UPDATE: Turns out I was installing to the wrong place, being Program Files. Once I installed to the appropriate location (C:\Users\xxxxxx\AppData\Roaming\Sublime Text 3\Packages\ApigeeSweetLime) all the commands were there.

**Comment by girishbr** [comment]
@durkode is right.

Since Sweetlime is not available via Package Control - please use the following command to install it correctly 

`git clone git@github.com:apigee/Sweetlime.git ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/ApigeeSweetLime'
